### ISSUE TITLE
Tonkeeper - IOS - When you click on last transaction error is occurred and app is being freezed

### ISSUE THREAD

**Issue by artitanov** [ton-blockchain/wallet-ios#11]
### Bug Type

Functional

### Reproduction steps

1. Open Tonkeeper
2. Click on last transaction
3. Error occured while loading transaction.
4. There are two options but no one is clickable

### Actual result

App is being freezed.
Closing the app and re-launch is not working. I’m not able to to do anything in app.
![74C1B7C9-3DA3-431F-B8B3-AF53FCECA047](https://user-images.githubusercontent.com/45713886/190663360-ff9a8ce7-6df2-433a-bcbf-d4a358f053f3.png)

### Expected result

Opportunity to copy log or restart app by clicking such button is available

### Suggested Severity

High

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):
- Device: iphone xs
- OS: ios 15.6.1
- Browser tonkeeper app
- Version 2.6

### Additional Context

Not rooted

**Comment by menschee** [comment]
Hi! This repo is intended for TON wallet app, not for Tonkeeper. If you have found any bugs with Tonkeeper app, please, open an issue [in this repository](https://github.com/tonkeeper/wallet)

**Comment by artitanov** [comment]
Hi, @menschee 
Sorry for choosing incorrect project for that issue. Raised another ticket under the right board.
Closing.
