### ISSUE TITLE
Tonkeeper - IOS - When you click on send button, history of addresses are available but the address is not shown (e.g. start and end of address)

### ISSUE THREAD

**Issue by artitanov** [ton-blockchain/wallet-ios#12]
### Bug Type

Functional

### Reproduction steps

1. Open Tonkeeper
2. Click on [send] button
3. History of last addresses are available, but addresses can not be defined

### Actual result

History of last addresses are available, but addresses can not be defined
![CA25B6D5-4ED3-4302-BFE8-5B99F1E937BB](https://user-images.githubusercontent.com/45713886/190665285-a386abb6-52f3-4f70-8c84-2e7886529ccb.jpeg)

### Expected result

History of last addresses are available, addresses can be defined (e.g. start and end of address)

### Suggested Severity

Medium

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):
- Device: iphone xs
- OS: ios 15.6.1
- Browser tonkeeper app
- Version 2.6

### Additional Context

Not rooted

**Comment by menschee** [comment]
Hi! This repo is intended for TON wallet app, not for Tonkeeper. If you have found any bugs with Tonkeeper app, please, open an issue [in this repository](https://github.com/tonkeeper/wallet)

**Comment by EmelyanenkoK** [comment]
Wrong repository.
