### ISSUE TITLE
Unlimited passcode trials

### ISSUE THREAD

**Issue by zmxv** [ton-blockchain/wallet-ios#13]
### Bug Type

Security

### Reproduction steps

1. Set up a wallet and a four digit passcode.
2. Restart the wallet app and start entering wrong passcodes.

### Actual result

A user can try passcodes as many times as possible.

![IMG_8454](https://user-images.githubusercontent.com/363061/190675633-c7a9ccbe-c291-4d96-a639-b3be64bfb8be.jpg)

### Expected result

Rate limiting (with exponential backoff) should be enforced to prevent brute force attack.
And passcode should not be limited to four digits only.

### Suggested Severity

High

### Device

Desktop (please complete the following information):

Smartphone (please complete the following information):
- Device: iPhone 13 Pro
- OS: iOS 15.6.1
- Browser: Mobile Safari
- Version: Tonkeeper 2.6

**Comment by menschee** [comment]
Hi! This repo is intended for TON wallet app, not for Tonkeeper. If you have found any bugs with Tonkeeper app, please, open an issue [in this repository](https://github.com/tonkeeper/wallet)

**Comment by zmxv** [comment]
Thanks for the pointer.
