### ISSUE TITLE
AppStore release

### ISSUE THREAD

**Issue by roman-rr** [ton-blockchain/wallet-ios#6]
Does anybody try to push release version into store ? Any success ?

**Comment by Kylmakalle** [comment]
@roman-rr While TON & Gram are not publicly released and available, I don’t think there’s a reason to make AppStore release.

I have managed to build, improve and publish app in TestFlight, you can find all the info in channel https://t.me/NiceGramWallet

**Comment by roman-rr** [comment]
@Kylmakalle 
Just in a case to create some alternative wallet with TON supports. 
**Nicegram** exactly what i want to do. 

When i trying to push archive into store i stuck here: 

> ITMS-90429: Invalid Swift Support - The files libswiftDarwin.dylib, libswiftMetal.dylib, libswiftCoreAudio.dylib, libswiftsimd.dylib, libswiftQuartzCore.dylib, libswiftos.dylib, libswiftObjectiveC.dylib, libswiftDispatch.dylib, libswiftCoreGraphics.dylib, libswiftCoreFoundation.dylib, libswiftUIKit.dylib, libswiftCoreMedia.dylib, libswiftAVFoundation.dylib, libswiftCore.dylib, libswiftFoundation.dylib, libswiftCoreImage.dylib aren’t at the expected location /Payload/TON Wallet.app/Frameworks. Move the file to the expected location, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

Tried to wrap all submodules into frameworks, but `ton` submodules seems pretty complicated. 
In your fork this is solved already ?

**Comment by Kylmakalle** [comment]
I've used guide from readme and built ipa file as explained in point 5

**Comment by roman-rr** [comment]
@Kylmakalle thanks now it’s clear, I used point 6.

**Comment by roman-rr** [comment]
@Kylmakalle by the way, how you can fully edit application without xcode project and just with IPA ?  (I saw in Nicegram notifications did implemented)

**Comment by Kylmakalle** [comment]
You can generate project with p. 6 and make all required edits, but build ipa with p. 5
